# Generated by Django 6.0.2 on 2026-02-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date', 'transaction_type'], name='transaction_user_id_257a00_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category', 'transaction_type', 'date'], name='transaction_user_id_c5329e_idx'),
        ),
    ]
